name: CHAP_docs
channels:
  - conda-forge
  - hexrd
  - nodefaults
dependencies:
  - python>=3.9,<3.11
  - numpy
  - pydantic
  - pyyaml
  - asteval
  - astra-toolbox
  - certif-pyspec
  - chess_scanparsers
  - fabio
  - flask
  - hexrd
  - lmfit
  - matplotlib
  - mpi4py
  - nexpy
  - pyfai
  - scikit-image
  - scipy
  - sympy
  - tomopy
