name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Grants write permissions to the job

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx # Install all necessary sphinx packages
          pip install sphinx-autodoc2
          #pip install python-docs-theme # Python Documentation theme
          pip install sphinx-rtd-theme # Read the Docs theme
          pip install myst-parser # Allow adding a Markdown (.md) file
                                  # to a toctree in an reStructuredText
                                  # (.rst) file
          pip install -r requirements.txt

      - name: Install package
        run: pip install -e .

#      - name: Generate .rst files with sphinx-apidoc
#        run: sphinx-apidoc -o docs src
#
      - name: Build Sphinx HTML documentation
        run: |
          make html
        working-directory: docs

      - name: List generated files
        run: |
          pwd
          ls -lha
          find ./docs/_build/html -type f

  deploy:
    needs: build
    runs-on: ubuntu-latest
    # Only run this job when pushing to the main branch
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: peaceiris/actions-gh-pages@v4 # Action to deploy to gh-pages branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: docs/_build/html
        force_orphan: true
